# Site settings
title: mmhan
email: contact@mmhan.net
description: > # this means to ignore newlines until "baseurl:"
  This is a personal blog of Mike Myat Min Han @ mmhan.
  I talk about my musings and technology, at times.
baseurl: ""	#path to site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: mmhan
github_username:  mmhan
timezone: Asia/Rangoon
excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: ""
    values:
      author: mmhan

# Build settings
markdown: kramdown
#lsi: true

kramdown:
  input: GFM