# Site settings
title: mmhan
description: > # this means to ignore newlines until "baseurl:"
  This is a personal blog of Mike Myat Min Han @ mmhan.
  I talk about my musings and technology, at times.
email: contact@mmhan.net
author: mmhan
baseurl: ""	#path to site
url: "http://mmhan.net" # the base hostname & protocol for your site
twitter_username: mmhan
github_username:  mmhan
timezone: Asia/Rangoon
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/index/:num/"
gems: [jekyll-paginate]

## Octopress's additional configs
subtitle: > # this means to ignore newlines until "baseurl:" # A description used in the header
  This is a personal blog of Mike Myat Min Han @ mmhan.
  I talk about my musings and technology, at times.
# simple_search:      # Search engine for simple site search
# date_format:        # Format dates using Ruby's date strftime syntax
# subscribe_rss:      # Url for your blog's feed, defauts to /atom.xml
# subscribe_email:    # Url to subscribe by email (service required)
# category_feeds:     # Enable per category RSS feeds (defaults to false in 2.1)
# email:              # Email address for the RSS feed if you want it.


defaults:
  -
    scope:
      path: ""
    values:
      author: mmhan
      layout: post

# Build settings
markdown: redcarpet
#lsi: true

kramdown:
  input: GFM